"""BrainFrog P1.4B Agent Profile Registry & Resolution.

Provides the canonical registry interface and deterministic profile resolution:
- AGENT PROFILE ≠ AUTHORIZATION
- REGISTRY ≠ AUTHORITY
- ROUTING ≠ AUTHORIZATION
- RESOLUTION ≠ EXECUTION

Re-exports AgentProfileRegistry, ProfileResolutionRequest, ProfileResolutionResult,
ProfileResolutionStatus, and resolution exceptions from core.runtime.agent_profile
to provide a dedicated registry and resolution module without duplicating domain state.
"""
from __future__ import annotations

from core.runtime.agent_profile import (
    CURRENT_AGENT_PROFILE_SCHEMA_VERSION,
    CURRENT_PROFILE_RESOLUTION_SCHEMA_VERSION,
    DOMAIN_MATCH_WEIGHT,
    MAX_CONSTRAINTS_COUNT,
    MAX_DESCRIPTION_CHARS,
    MAX_DISPLAY_NAME_CHARS,
    MAX_DOMAIN_CHARS,
    MAX_DOMAINS_COUNT,
    MAX_METADATA_DEPTH,
    MAX_METADATA_KEYS,
    MAX_PROFILE_ID_CHARS,
    MAX_PROFILE_SERIALIZED_BYTES,
    MAX_REGISTRY_CAPACITY,
    MAX_RESOLUTION_CANDIDATE_IDS,
    MAX_RESOLUTION_DOMAIN_CHARS,
    MAX_RESOLUTION_REASON_CHARS,
    MAX_RESOLUTION_REQUEST_SERIALIZED_BYTES,
    MAX_RESOLUTION_RESULT_SERIALIZED_BYTES,
    MAX_RESOLUTION_SKILL_CHARS,
    MAX_RESOLUTION_SKILLS_COUNT,
    MAX_RESOLUTION_TASK_TYPE_CHARS,
    MAX_SKILL_CHARS,
    MAX_SKILLS_COUNT,
    MAX_TASK_TYPE_CHARS,
    MAX_TASK_TYPES_COUNT,
    SKILL_MATCH_WEIGHT,
    TASK_TYPE_MATCH_WEIGHT,
    AgentProfile,
    AgentProfileAuthorityViolationError,
    AgentProfileDuplicateError,
    AgentProfileError,
    AgentProfileIntegrityError,
    AgentProfileNotFoundError,
    AgentProfileRegistry,
    AgentProfileValidationError,
    AmbiguousProfileResolutionError,
    NoMatchingProfileError,
    ProfileResolutionRequest,
    ProfileResolutionResult,
    ProfileResolutionStatus,
    resolve_profile,
    validate_profile_id,
)

__all__ = [
    "AgentProfile",
    "AgentProfileRegistry",
    "ProfileResolutionRequest",
    "ProfileResolutionResult",
    "ProfileResolutionStatus",
    "AgentProfileError",
    "AgentProfileValidationError",
    "AgentProfileAuthorityViolationError",
    "AgentProfileIntegrityError",
    "AgentProfileDuplicateError",
    "AgentProfileNotFoundError",
    "AmbiguousProfileResolutionError",
    "NoMatchingProfileError",
    "resolve_profile",
    "CURRENT_AGENT_PROFILE_SCHEMA_VERSION",
    "CURRENT_PROFILE_RESOLUTION_SCHEMA_VERSION",
    "MAX_PROFILE_ID_CHARS",
    "MAX_DISPLAY_NAME_CHARS",
    "MAX_DESCRIPTION_CHARS",
    "MAX_TASK_TYPES_COUNT",
    "MAX_TASK_TYPE_CHARS",
    "MAX_DOMAINS_COUNT",
    "MAX_DOMAIN_CHARS",
    "MAX_SKILLS_COUNT",
    "MAX_SKILL_CHARS",
    "MAX_CONSTRAINTS_COUNT",
    "MAX_METADATA_KEYS",
    "MAX_METADATA_DEPTH",
    "MAX_PROFILE_SERIALIZED_BYTES",
    "MAX_REGISTRY_CAPACITY",
    "MAX_RESOLUTION_TASK_TYPE_CHARS",
    "MAX_RESOLUTION_DOMAIN_CHARS",
    "MAX_RESOLUTION_SKILLS_COUNT",
    "MAX_RESOLUTION_SKILL_CHARS",
    "MAX_RESOLUTION_CANDIDATE_IDS",
    "MAX_RESOLUTION_REASON_CHARS",
    "MAX_RESOLUTION_REQUEST_SERIALIZED_BYTES",
    "MAX_RESOLUTION_RESULT_SERIALIZED_BYTES",
    "TASK_TYPE_MATCH_WEIGHT",
    "DOMAIN_MATCH_WEIGHT",
    "SKILL_MATCH_WEIGHT",
    "validate_profile_id",
]
