"""BrainFrog Phase 5 — SDK Typed Events and Subscription.

Defines the typed event lifecycle, event broker, and bounded/scrubbed payloads.
Events are strictly generated by trusted runtime code.

Product Thesis:
    "Don't just trust the agent. Verify it."
"""
from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
import logging
import threading
from typing import Any, AsyncIterator, Callable, Dict, List, Optional, Set, Tuple

from core.runtime.proof import capture_bounded_output, redact_secrets
from core.runtime.secret_scrubbing import scrub_secrets

logger = logging.getLogger(__name__)


class EventType(str, Enum):
    """Authoritative lifecycle event types."""

    TASK_CREATED = "TASK_CREATED"
    PLAN_CREATED = "PLAN_CREATED"
    TRANSACTION_STARTED = "TRANSACTION_STARTED"
    STEP_STARTED = "STEP_STARTED"
    PROCESS_STARTED = "PROCESS_STARTED"
    PROCESS_COMPLETED = "PROCESS_COMPLETED"
    TEST_STARTED = "TEST_STARTED"
    TEST_COMPLETED = "TEST_COMPLETED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    PROOF_CREATED = "PROOF_CREATED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_CANCELLED = "TASK_CANCELLED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"


@dataclass(frozen=True)
class SDKEvent:
    """Typed, correlated, and scrubbed runtime lifecycle event."""

    event_type: EventType
    task_id: str
    session_id: str
    timestamp: str  # ISO 8601 UTC
    transaction_id: Optional[str] = None
    process_id: Optional[str] = None
    payload: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "event_type": self.event_type.value,
            "task_id": self.task_id,
            "session_id": self.session_id,
            "timestamp": self.timestamp,
            "transaction_id": self.transaction_id,
            "process_id": self.process_id,
            "payload": self.payload,
        }


def sanitize_event_payload(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Sanitize and bound an event payload before emission.

    - Scrubs secrets and auth tokens.
    - Caps stdout/stderr using bounded output retention.
    - Strips environment dictionaries.
    """
    clean: Dict[str, Any] = {}
    for k, v in payload.items():
        if k in ("env", "environment", "environ"):
            continue  # Never leak raw environment variables
        if isinstance(v, str):
            scrubbed = scrub_secrets(v)
            redacted = redact_secrets(scrubbed)
            if k in ("stdout", "stderr", "output", "test_output", "log"):
                bounded, _ = capture_bounded_output(redacted, max_bytes=10000)
                clean[k] = bounded
            else:
                clean[k] = redacted
        elif isinstance(v, dict):
            clean[k] = sanitize_event_payload(v)
        elif isinstance(v, (list, tuple)):
            clean[k] = [
                redact_secrets(scrub_secrets(str(item))) if isinstance(item, str) else item
                for item in v
            ]
        else:
            clean[k] = v
    return clean


def create_sdk_event(
    event_type: EventType,
    task_id: str,
    session_id: str,
    *,
    transaction_id: Optional[str] = None,
    process_id: Optional[str] = None,
    payload: Optional[Dict[str, Any]] = None,
    timestamp: Optional[str] = None,
) -> SDKEvent:
    """Construct an SDKEvent with trusted timestamps and sanitized payload."""
    ts = timestamp or datetime.now(timezone.utc).isoformat()
    safe_payload = sanitize_event_payload(payload or {})
    return SDKEvent(
        event_type=event_type,
        task_id=task_id,
        session_id=session_id,
        timestamp=ts,
        transaction_id=transaction_id,
        process_id=process_id,
        payload=safe_payload,
    )


DEFAULT_EVENT_QUEUE_MAXSIZE = 1000


class EventBroker:
    """Thread-safe and async-safe subscription broker for SDK lifecycle events.

    Guarantees:
    - Never mutates asyncio.Queue directly from a foreign thread.
    - Uses loop.call_soon_threadsafe for cross-thread queue updates.
    - Drops oldest events (FIFO eviction) when subscriber queue reaches maxsize.
    - Prevents unbounded memory accumulation from slow/abandoned subscribers.
    - Thread-safe listener registration and unregistration.
    """

    def __init__(self, default_maxsize: int = DEFAULT_EVENT_QUEUE_MAXSIZE) -> None:
        self._lock = threading.Lock()
        self._default_maxsize = default_maxsize
        # Maps task_id -> Set of (queue, loop)
        self._async_queues: Dict[str, Set[Tuple[asyncio.Queue[SDKEvent], Optional[asyncio.AbstractEventLoop]]]] = {}
        self._global_async_queues: Set[Tuple[asyncio.Queue[SDKEvent], Optional[asyncio.AbstractEventLoop]]] = set()
        self._sync_handlers: List[Callable[[SDKEvent], None]] = []

    def add_sync_handler(self, handler: Callable[[SDKEvent], None]) -> None:
        with self._lock:
            if handler not in self._sync_handlers:
                self._sync_handlers.append(handler)

    def remove_sync_handler(self, handler: Callable[[SDKEvent], None]) -> None:
        with self._lock:
            if handler in self._sync_handlers:
                self._sync_handlers.remove(handler)

    def subscribe_async(
        self,
        task_id: Optional[str] = None,
        maxsize: Optional[int] = None,
    ) -> asyncio.Queue[SDKEvent]:
        """Subscribe an asyncio queue to lifecycle events.

        Captures the calling thread's running event loop for thread-safe cross-thread emission.
        """
        eff_maxsize = maxsize if maxsize is not None else self._default_maxsize
        q: asyncio.Queue[SDKEvent] = asyncio.Queue(maxsize=eff_maxsize)
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        item = (q, loop)
        with self._lock:
            if task_id:
                if task_id not in self._async_queues:
                    self._async_queues[task_id] = set()
                self._async_queues[task_id].add(item)
            else:
                self._global_async_queues.add(item)
        return q

    def unsubscribe_async(self, q: asyncio.Queue[SDKEvent], task_id: Optional[str] = None) -> None:
        with self._lock:
            if task_id and task_id in self._async_queues:
                self._async_queues[task_id] = {item for item in self._async_queues[task_id] if item[0] is not q}
                if not self._async_queues[task_id]:
                    del self._async_queues[task_id]
            self._global_async_queues = {item for item in self._global_async_queues if item[0] is not q}

    def emit(self, event: SDKEvent) -> None:
        """Dispatch event synchronously to sync handlers and thread-safely to async queues."""
        with self._lock:
            handlers = list(self._sync_handlers)
            target_subs = list(self._global_async_queues)
            if event.task_id in self._async_queues:
                target_subs.extend(self._async_queues[event.task_id])

        # 1. Sync handlers (exceptions do not corrupt task execution)
        for h in handlers:
            try:
                h(event)
            except Exception as exc:
                logger.warning(f"Sync event listener raised exception: {exc}")

        # 2. Async queues (thread-safe dispatch to loop)
        def _enqueue(queue: asyncio.Queue[SDKEvent], ev: SDKEvent) -> None:
            try:
                if queue.full():
                    try:
                        queue.get_nowait()  # Evict oldest event to bound memory
                    except (asyncio.QueueEmpty, Exception):
                        pass
                queue.put_nowait(ev)
            except Exception:
                pass

        for q, loop in target_subs:
            if loop is not None and not loop.is_closed():
                try:
                    loop.call_soon_threadsafe(_enqueue, q, event)
                except RuntimeError:
                    # Loop was closed concurrently
                    pass
            else:
                _enqueue(q, event)

    def clear(self) -> None:
        """Clear all registered event listeners and queues."""
        with self._lock:
            self._sync_handlers.clear()
            self._async_queues.clear()
            self._global_async_queues.clear()


__all__ = [
    "EventType",
    "SDKEvent",
    "EventBroker",
    "create_sdk_event",
    "sanitize_event_payload",
]
